# Generated by Django 4.1.2 on 2022-11-18 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.CharField(default='[]', max_length=200),
        ),
    ]
