# Generated by Django 4.1.2 on 2022-11-21 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
        ('likes', '0001_initial'),
        ('comments', '0001_initial'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authors.author')),
                ('comments', models.ManyToManyField(blank=True, to='comments.comment')),
                ('likes', models.ManyToManyField(blank=True, to='likes.like')),
                ('posts', models.ManyToManyField(blank=True, to='posts.post')),
            ],
        ),
    ]
