# Generated by Django 4.1.2 on 2022-11-21 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbox',
            name='object',
        ),
    ]
