# Generated by Django 4.1.2 on 2022-11-21 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('posts', '0001_initial'),
        ('likes', '0001_initial'),
        ('inbox', '0002_remove_inbox_object'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbox',
            name='commentid',
        ),
        migrations.RemoveField(
            model_name='inbox',
            name='likeid',
        ),
        migrations.RemoveField(
            model_name='inbox',
            name='postid',
        ),
        migrations.AddField(
            model_name='inbox',
            name='comments',
            field=models.ManyToManyField(blank=True, to='comments.comment'),
        ),
        migrations.AddField(
            model_name='inbox',
            name='likes',
            field=models.ManyToManyField(blank=True, to='likes.like'),
        ),
        migrations.AddField(
            model_name='inbox',
            name='posts',
            field=models.ManyToManyField(blank=True, to='posts.post'),
        ),
    ]
