# Generated by Django 4.1.2 on 2022-10-23 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.URLField(default='<django.db.models.fields.URLField><django.db.models.fields.UUIDField>'),
        ),
    ]
