# Generated by Django 4.1.2 on 2022-10-24 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_alter_author_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='type',
        ),
    ]
