# Generated by Django 4.1.2 on 2022-10-23 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SingleAuthor',
            fields=[
                ('type', models.CharField(max_length=200)),
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('url', models.CharField(max_length=200)),
                ('host', models.CharField(max_length=200)),
                ('displayName', models.CharField(max_length=200)),
                ('github', models.CharField(max_length=200)),
                ('profileImage', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('items', models.ManyToManyField(to='authors.singleauthor')),
            ],
        ),
    ]
