# Generated by Django 4.1.2 on 2022-10-24 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_alter_comment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content_type',
            new_name='contentType',
        ),
    ]
