# Generated by Django 4.1.2 on 2022-10-21 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment', models.CharField(max_length=500)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('id', models.CharField(max_length=250, primary_key=True, serialize=False)),
            ],
        ),
    ]
