# Generated by Django 4.1.2 on 2022-10-21 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('comment', '0003_alter_comment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.AddField(
            model_name='comment',
            name='comments',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='comments.comments'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(default='<django.db.models.fields.related.ForeignKey>/<function uuid4 at 0x7f10687b64d0>', editable=False, max_length=250, primary_key=True, serialize=False),
        ),
    ]
