# Generated by Django 4.1.2 on 2022-10-21 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_alter_comments_id'),
        ('comment', '0004_remove_comment_author_comment_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comments',
            field=models.ForeignKey(default='replacewithpost/c21f6084-2908-40fb-bfd9-d379c657e0bd', on_delete=django.db.models.deletion.CASCADE, to='comments.comments'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(default='<django.db.models.fields.related.ForeignKey>/13dbf10c-dd8f-4e44-a1e5-64f358d2f492', editable=False, max_length=250, primary_key=True, serialize=False),
        ),
    ]
