# Generated by Django 4.1.2 on 2022-10-21 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_alter_comment_comments_alter_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(default='<django.db.models.fields.related.ForeignKey>/f91764e1-c387-4503-80c0-c2ab1c429848', editable=False, max_length=250, primary_key=True, serialize=False),
        ),
    ]
