# Generated by Django 4.1.2 on 2022-10-21 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0006_alter_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(default='<django.db.models.fields.related.ForeignKey>/b23475c2-7128-486c-828b-c6be4c3ba56a', editable=False, max_length=250, primary_key=True, serialize=False),
        ),
    ]
