# Generated by Django 4.1.2 on 2022-10-21 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0007_alter_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(default='<django.db.models.fields.related.ForeignKey>/b19ea355-7208-491d-9968-5a5a724121c8', max_length=250, primary_key=True, serialize=False),
        ),
    ]
