# Generated by Django 4.1.2 on 2022-10-22 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0010_alter_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(default='<django.db.models.fields.related.ForeignKey>/3f622fde-a602-44d1-bfb2-b587a4b5644d', max_length=250, primary_key=True, serialize=False),
        ),
    ]
