# Generated by Django 4.1.2 on 2022-10-22 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0011_alter_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(default='<django.db.models.fields.related.ForeignKey>/f846729e-ff10-452a-955c-ba23d6b6b756', max_length=250, primary_key=True, serialize=False),
        ),
    ]
