# Generated by Django 4.1.2 on 2022-10-22 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0012_alter_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(default='<django.db.models.fields.related.ForeignKey>/46e2ce21-ec47-4583-8464-e8b6738a2703', max_length=250, primary_key=True, serialize=False),
        ),
    ]
