# Generated by Django 4.1.2 on 2022-10-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0013_alter_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(default='<django.db.models.fields.related.ForeignKey>/12448ad3-f729-408d-b4b2-ad2bc8a8cc43', max_length=250, primary_key=True, serialize=False),
        ),
    ]
