# Generated by Django 4.1.2 on 2022-11-17 07:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0002_author_user_alter_author_displayname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('context', models.URLField()),
                ('summary', models.CharField(max_length=200)),
                ('object', models.URLField()),
                ('postid', models.UUIDField(null=True)),
                ('commentid', models.UUIDField(null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authors.author')),
            ],
        ),
    ]
