# Generated by Django 4.1.2 on 2022-11-17 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('comments', '0001_initial'),
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='commentid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='comments.comment'),
        ),
        migrations.AlterField(
            model_name='like',
            name='postid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.post'),
        ),
    ]
