# Generated by Django 4.1.2 on 2022-10-21 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('page', models.IntegerField()),
                ('size', models.IntegerField()),
                ('id', models.CharField(default='replacewithpost/<function uuid4 at 0x7f10687b64d0>', editable=False, max_length=250, primary_key=True, serialize=False)),
            ],
        ),
    ]
