# Generated by Django 4.1.2 on 2022-10-21 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='id',
            field=models.CharField(default='replacewithpost/eb02c846-e3ec-4568-a2cb-37f4051b7cbc', editable=False, max_length=250, primary_key=True, serialize=False),
        ),
    ]
