# Generated by Django 4.1.2 on 2022-10-21 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_alter_comments_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='id',
            field=models.CharField(default='replacewithpost/6d309a4c-150b-441f-a10a-cca24ba8e367', editable=False, max_length=250, primary_key=True, serialize=False),
        ),
    ]
