# Generated by Django 4.1.2 on 2022-10-21 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_alter_comments_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='id',
            field=models.CharField(default='replacewithpost/35ff47f6-e819-4a51-857d-71166654d1de', editable=False, max_length=250, primary_key=True, serialize=False),
        ),
    ]
