# Generated by Django 4.1.2 on 2022-10-21 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_alter_comments_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='id',
            field=models.CharField(default='replacewithpost/de9a7559-eda0-4763-9bbc-ec6b6587bc69', max_length=250, primary_key=True, serialize=False),
        ),
    ]
