# Generated by Django 4.1.2 on 2022-10-21 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_alter_comments_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='id',
            field=models.CharField(default='replacewithpost/d36bf67d-0af1-45be-9b6c-967f54206720', max_length=250, primary_key=True, serialize=False),
        ),
    ]
