# Generated by Django 4.1.2 on 2022-10-21 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_alter_comments_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='id',
            field=models.CharField(default='replacewithpost/90a060ae-fc9c-43cd-a1af-902127e2e17a', max_length=250, primary_key=True, serialize=False),
        ),
    ]
