# Generated by Django 4.1.2 on 2022-10-22 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0007_alter_comments_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='id',
            field=models.CharField(default='replacewithpost/11273fc4-78de-4a76-b9df-3fcc848f22ea', max_length=250, primary_key=True, serialize=False),
        ),
    ]
