# Generated by Django 4.1.2 on 2022-10-22 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0009_alter_comments_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='id',
            field=models.CharField(default='replacewithpost/5ccd1608-f156-4c9e-96e8-1dbee8466e03', max_length=250, primary_key=True, serialize=False),
        ),
    ]
