# Generated by Django 4.1.2 on 2022-10-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0010_alter_comments_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='id',
            field=models.CharField(default='replacewithpost/57ba928a-cbc4-4a45-99f4-93185b9ee1a8', max_length=250, primary_key=True, serialize=False),
        ),
    ]
